### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'. Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload

### ISSUE THREAD

**Issue by illia-code-care** [DarkaOnLine/L5-Swagger#431]
- L5-Swagger Version: 8.0
- PHP Version: 8.0
- OS: Ubuntu

### Description:

Locally works. After installing on server got:

Uncaught SyntaxError: Unexpected token '<'
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload

### Steps To Reproduce

1. composer require ..
2. php artisan l5-swagger:generate
3. php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

After accessing /documentation there are 2 errors in console.

**Comment by DarkaOnLine** [comment]
Looks like something is wrong with your  `resources/views/index.blade.php` - https://github.com/DarkaOnLine/L5-Swagger/blob/master/resources/views/index.blade.php

Can you check if it is published correctly and you don't see any syntax error in file?

**Comment by illia-code-care** [comment]
@DarkaOnLine 
As I see I have syntax error in this files:

<script src="{{ l5_swagger_asset($documentation, 'swagger-ui-bundle.js') }}"> </script>
<script src="{{ l5_swagger_asset($documentation, 'swagger-ui-standalone-preset.js') }}"> </script>

In each of them I get error: Uncaught SyntaxError: Unexpected token '<'. But I can not get into them.

And I guess that's why after this lines I get:
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload
because I think Bundle depends on that 2 scripts.

**Comment by illia-code-care** [comment]
@DarkaOnLine 

I copied github blade to my file but still the same. I think there are 2 errors in swagger-ui-bundle.js, swagger-ui-standalone-preset.js each of them.

**Comment by illia-code-care** [comment]
![image](https://user-images.githubusercontent.com/88253671/148929608-ddd6f46a-c8fc-4045-a203-b68d92b1122f.png)

**Comment by DarkaOnLine** [comment]
We require ` "swagger-api/swagger-ui": "^3.0"` in our composer.json. You can try to use older version of this in your composer - assuming swagger-ui have a bug in their release :(

**Comment by illia-code-care** [comment]
![image](https://user-images.githubusercontent.com/88253671/148929955-af36e5e9-e757-43bd-947e-f3b3e5b7ad03.png)

**Comment by illia-code-care** [comment]
I tries with Chrome, Vivaldi but the same.. @DarkaOnLine 
Ok I gonna try older version, thanks!

**Comment by awwwer** [comment]
Is there any update on this? I'm having the same issue when I'm trying to load the documentation.
`
swagger-ui-bundle.js…de593c255f23632e2:1 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js…593c255f23632e2:1:1)
swagger-ui-standalon…8b3f0c5a355d677f4:1 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalon…3f0c5a355d677f4:1:1)
documentation:37 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (documentation:37:20)`

**Comment by adeel94mirza** [comment]
Having the same issue, any update?

**Comment by shk-webpr** [comment]
![image](https://user-images.githubusercontent.com/74294262/193296276-7cae6484-002a-4c3d-b667-81008a144aa4.png)

Script tags crawled up a few characters. After I changed `title` in the config file to English, the problem was solved.
Probably a multibyte string issue.

**Comment by shk-webpr** [comment]
For me, the problem was [mbstring.func_overload=2](https://www.php.net/manual/en/mbstring.overload.php).

**Comment by abkrim** [comment]
At today, 25/01/2023 problem persist.

![castris 2023-01-25 a las 12 28 11](https://user-images.githubusercontent.com/1238625/214552102-e6d71bea-99f7-47f3-83b8-b8a2dc97812c.jpg)

@shk-webpr You can explain you solution ? Thanks.

**Comment by shk-webpr** [comment]
@abkrim, my solution was one of these:
- setting `title` value in English in config file `l5-swagger.php`;
![image](https://user-images.githubusercontent.com/74294262/214577320-7001e7a9-bc1a-4820-82cd-f4ac31b8184b.png)

- setting `mbstring.func_overload=0` in PHP .ini files.

**Comment by zhangjiaying** [comment]
try add the below config to NginX server config

charset utf-8;

**Comment by Danifantonrxd** [comment]
My solution was adding the method serveFiles

const CSS_URL = 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.1.0/swagger-ui.min.css';

const options = {
  customCssUrl: CSS_URL,
};

router.use('/api-docs', swaggerUi.serveFiles(swaggerDoc, options), swaggerUi.setup(swaggerDoc, options));

I had to add the styles manually. it work for me :)

**Comment by danexcode** [comment]
I will add to my solution the calling of swagger-ui-dist package,

const { SwaggerUIBundle, SwaggerUIStandalonePreset } = require('swagger-ui-dist');

I made tests and that line is necesary

**Comment by nani-samireddy** [comment]
> I will add to my solution the calling of swagger-ui-dist package,
> 
> const { SwaggerUIBundle, SwaggerUIStandalonePreset } = require('swagger-ui-dist');
> 
> I made tests and that line is necessary

I confirm that this method also works for me. Thank you for your help. For future reference, this is my repository.
[](https://github.com/nani-samireddy/swagger-api-documentation-nodejs)

**Comment by SirPeace** [comment]
During local development I forgot to set the `FORCE_HTTPS=false` in .env.

So it tried to load scripts from https://localhost and resulted into a blank page with this error in a console.

**Comment by sheraz4196** [comment]
> I will add to my solution the calling of swagger-ui-dist package,

> const { SwaggerUIBundle, SwaggerUIStandalonePreset } = require('swagger-ui-dist');

> I made tests and that line is necesary

Holy Shit!!! It really worked. Thanks  @danexcode
